### ISSUE TITLE
Error running  demo_MiddleBury_slowmotion.py  too many indices for array

### ISSUE THREAD

**Issue by andkonstan** [baowenbo/DAIN#106]
Hi! Thanks for reading. When I am trying to rundemo_MiddleBury_slowmotion.py I get the following error:

Traceback (most recent call last):
  File "demo_MiddleBury_slowmotion.py", line 156, in <module>
    intPaddingLeft: intPaddingLeft+intWidth], (1, 2, 0)) for item in y_]
  File "demo_MiddleBury_slowmotion.py", line 156, in <listcomp>
    intPaddingLeft: intPaddingLeft+intWidth], (1, 2, 0)) for item in y_]
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

Thanks for your help!

**Comment by andkonstan** [comment]
I run the demo with the wrong command the correct one is:
CUDA_VISIBLE_DEVICES=0 python demo_MiddleBury_slowmotion.py --netName DAIN_slowmotion --time_step 0.25
