### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by LMNlmn31415** [baowenbo/DAIN#110]
When I try to interpolate the frame with the processed grayscale image, an error occurs：ValueError: axes don't match array

  X0 =  torch.from_numpy( np.transpose(imread(arguments_strFirst) , (2,0,1)).astype("float32")/ 255.0).type(dtype)
Traceback (most recent call last):
  File "modify_demo_MiddleBury.py", line 121, in <module>
    X0 =  torch.from_numpy( np.transpose(imread(arguments_strFirst) , (2,0,1)).astype("float32")/ 255.0).type(dtype)            
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 598, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by fedhere** [comment]
I am getting the same error, any resolution?
