### ISSUE TITLE
Does not install on Ubuntu 20.04

### ISSUE THREAD

**Issue by lgmventura** [baowenbo/DAIN#123]
Following the installation instructions I ran out into an error that there must be a Conda environment called `pytorch1.0.0` after running `./build.sh`  – this is not mentioned in the compilation instructions. Well, I created a Conda environment called `pytorch1.0.0` and installed pytorch v1.4.0 (I saw on issue #118 that newer versions of pytorch aren't compatible, this is also not on the instructions) and ran `build.sh` again. Now, I come to:

```
(pytorch1.0.0) luiz@luiz-Aspire-V3-772:[/media/luiz/Volume/Downloads/DAIN/my_package]: ./build.sh
Need pytorch>=1.0.0
./build.sh: line 4: activate: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/media/luiz/Volume/anaconda3/envs/pytorch1.0.0/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

**Comment by iBobbyTS** [comment]
This seems like your CUDA toolkit is not installed correctly, try the following command to check it torch is compatible with CUDA
```
import torch
torch.Tensor([1.]).cuda()
```
You should not get warnings or errors for this code. 
Did you install cuda from nvidia? And is PyTorch from pip or conda, did you choose the correct cuda version?

**Comment by nanojin** [comment]
I tried this after installing pytorch:
`$ python -c "import torch; torch.Tensor([1.]).cuda()"`

This is my result.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/~/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by iBobbyTS** [comment]
This means you don't have an Nvidia GPU or the driver is not installed correctly. 
You have to have an Nvidia GPU, not AMD or Integrated.

**Comment by iBobbyTS** [comment]
Run `nvidia-smi` to check the GPU status, you should get something like this
<img width="721" alt="Screen Shot 2020-12-10 at 7 40 35 AM" src="https://user-images.githubusercontent.com/46138297/101702054-1aed8080-3abb-11eb-9edb-e2eb237ae8f6.png">
Make sure there's a CUDA Version at the top right. 
And find the command to install torch on [PyTorch 1.4.0 installation command](https://pytorch.org/get-started/previous-versions/#v140), select the correct system, and CUDA version.

**Comment by lgmventura** [comment]
I reinstalled my nVidia drivers entirely (currently using nvidia 450, cuda v.11), created the conda environment called pytorch1.0.0 (`conda create -n pytorch1.0.0`) and ran what I found [in the pytorch's website](https://pytorch.org/get-started/previous-versions/):
```
conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch
```
It now **compiled and installed.** I will test it later. Thank you so much for the support.

I'll close the issue for now.

**Comment by courtens** [comment]
running `conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch` got me:

````
failed                                                                                                                              

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchvision==0.2.1 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

````
Is it a requirement to run the installation as root?

Getting DAIN running on Ubuntu 20.04 turns out to be difficult. 

`./build.sh` returns:

<pre>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;setup.py&quot;, line 10, in &lt;module&gt;
    setup(
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py&quot;, line 153, in setup
    return distutils.core.setup(**attrs)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/core.py&quot;, line 148, in setup
    dist.run_commands()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/dist.py&quot;, line 966, in run_commands
    self.run_command(cmd)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py&quot;, line 67, in run
    self.do_egg_install()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py&quot;, line 109, in do_egg_install
    self.run_command(&apos;bdist_egg&apos;)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/cmd.py&quot;, line 313, in run_command
    self.distribution.run_command(command)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py&quot;, line 164, in run
    cmd = self.call_command(&apos;install_lib&apos;, warn_dir=0)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py&quot;, line 150, in call_command
    self.run_command(cmdname)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/cmd.py&quot;, line 313, in run_command
    self.distribution.run_command(command)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/install_lib.py&quot;, line 11, in run
    self.build()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/command/install_lib.py&quot;, line 107, in build
    self.run_command(&apos;build_ext&apos;)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/cmd.py&quot;, line 313, in run_command
    self.distribution.run_command(command)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py&quot;, line 79, in run
    _build_ext.run(self)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py&quot;, line 186, in run
    _build_ext.build_ext.run(self)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/command/build_ext.py&quot;, line 340, in run
    self.build_extensions()
  File &quot;/home/nathaniel/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py&quot;, line 670, in build_extensions
    build_ext.build_extensions(self)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py&quot;, line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/command/build_ext.py&quot;, line 449, in build_extensions
    self._build_extensions_serial()
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/command/build_ext.py&quot;, line 474, in _build_extensions_serial
    self.build_extension(ext)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py&quot;, line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File &quot;/home/nathaniel/anaconda3/lib/python3.8/distutils/command/build_ext.py&quot;, line 528, in build_extension
    objects = self.compiler.compile(sources,
  File &quot;/home/nathaniel/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py&quot;, line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File &quot;/home/nathaniel/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py&quot;, line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File &quot;/home/nathaniel/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py&quot;, line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
</pre>

**Comment by YouweiLyu** [comment]
@courtens 
I create a new anaconda environment python=3.6 and run the installation successfully. python 3.8 env may be unsuitable for installing pytorch 1.0.0.
