### ISSUE TITLE
when I run "Interpolation" segment on colab.

### ISSUE THREAD

**Issue by xstrauss** [baowenbo/DAIN#78]
**# Interpolation
%shell mkdir -p '/content/gdrive/My Drive/DAIN/FRAMEOUT'
%cd /content/DAIN

!python colab_interpolate.py --netName DAIN --time_step 59.94 --start_frame 1   --end_frame 1800 --frame_input_dir '/content/gdrive/My Drive/DAIN/FRAMEIN' --frame_output_dir '/content/gdrive/My Drive/DAIN/FRAMEOUT'**

**when I try to run it, I encountered with this error;**

/content/DAIN
revise the unique id to a random numer 71993
Namespace(SAVED_MODEL=None, alpha=[0.0, 1.0], arg='./model_weights/71993-Fri-May-15-22:15/args.txt', batch_size=1, channels=3, ctx_lr_coe=1.0, datasetName='Vimeo_90K_interp', datasetPath='', dataset_split=97, debug=False, depth_lr_coe=0.001, dtype=<class 'torch.cuda.FloatTensor'>, end_frame=1800, epsilon=1e-06, factor=0.2, filter_lr_coe=1.0, filter_size=4, flow_lr_coe=0.01, force=False, frame_input_dir='/content/gdrive/My Drive/DAIN/FRAMEIN', frame_output_dir='/content/gdrive/My Drive/DAIN/FRAMEOUT', log='./model_weights/71993-Fri-May-15-22:15/log.txt', lr=0.002, netName='DAIN', no_date=False, numEpoch=100, occ_lr_coe=1.0, patience=5, rectify_lr=0.001, save_path='./model_weights/71993-Fri-May-15-22:15', save_which=1, seed=1, start_frame=1, time_step=59.94, uid=None, use_cuda=True, use_cudnn=1, weight_decay=0, workers=8)
cudnn is used
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.UpsamplingNearest2d is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "colab_interpolate.py", line 112, in <module>
    y_s, offset, filter = model(torch.stack((X0, X1),dim = 0))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/DAIN/networks/DAIN.py", line 167, in forward
    cur_offset_output,cur_filter_output)
  File "/content/DAIN/networks/DAIN.py", line 307, in FilterInterpolate_ctx
    ctx0_offset = FilterInterpolationModule()(ctx0,offset[0].detach(),filter[0].detach())
AttributeError: 'list' object has no attribute 'detach'

**Comment by AlphaGit** [comment]
Hey @xstrauss, I just published a new version of the Colab file that should be soon available in the master branch. In the meantime, you can get it from ([here](https://github.com/AlphaGit/DAIN/blob/colab-compatibility/Colab_DAIN.ipynb)). Why don't you give it a try? I think it might help with your issue.

**Comment by D3rel** [comment]
> Hey @xstrauss, I just published a new version of the Colab file that should be soon available in the master branch. In the meantime, you can get it from ([here](https://github.com/AlphaGit/DAIN/blob/colab-compatibility/Colab_DAIN.ipynb)). Why don't you give it a try? I think it might help with your issue.

Im getting a similar problem!! Can u help me how can i fix it??

"/content/DAIN
revise the unique id to a random numer 80321
Namespace(SAVED_MODEL=None, alpha=[0.0, 1.0], arg='./model_weights/80321-Tue-Jun-23-08-57/args.txt', batch_size=1, channels=3, ctx_lr_coe=1.0, datasetName='Vimeo_90K_interp', datasetPath='', dataset_split=97, debug=False, depth_lr_coe=0.001, dtype=<class 'torch.cuda.FloatTensor'>, end_frame=2020, epsilon=1e-06, factor=0.2, filter_lr_coe=1.0, filter_size=4, flow_lr_coe=0.01, force=False, frame_input_dir='/content/DAIN/input_frames', frame_output_dir='/content/DAIN/output_frames', log='./model_weights/80321-Tue-Jun-23-08-57/log.txt', lr=0.002, netName='DAIN_slowmotion', no_date=False, numEpoch=100, occ_lr_coe=1.0, patience=5, rectify_lr=0.001, save_path='./model_weights/80321-Tue-Jun-23-08-57', save_which=1, seed=1, start_frame=1, time_step=0.4995, uid=None, use_cuda=True, use_cudnn=1, weight_decay=0, workers=8)
cudnn is used
Interpolate 1 frames
*****************************************************************
**** We couldn't load any trained weights ***********************
*****************************************************************"
