### ISSUE TITLE
TypeError: ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by CheezyAmuzus** [baowenbo/DAIN#86]
I get this error when running `colab_interpolate.py` on the Google Colab provided by styler00dollar.

```
/content/DAIN
revise the unique id to a random numer 79035
Namespace(SAVED_MODEL=None, alpha=[0.0, 1.0], arg='./model_weights/79035-Fri-May-29-21:08/args.txt', batch_size=1, channels=3, ctx_lr_coe=1.0, datasetName='Vimeo_90K_interp', datasetPath='', dataset_split=97, debug=False, depth_lr_coe=0.001, dtype=<class 'torch.cuda.FloatTensor'>, end_frame=866, epsilon=1e-06, factor=0.2, filter_lr_coe=1.0, filter_size=4, flow_lr_coe=0.01, force=False, frame_input_dir='/content/DAIN/input_frames', frame_output_dir='/content/DAIN/output_frames', log='./model_weights/79035-Fri-May-29-21:08/log.txt', lr=0.002, netName='DAIN_slowmotion', no_date=False, numEpoch=100, occ_lr_coe=1.0, patience=5, rectify_lr=0.001, save_path='./model_weights/79035-Fri-May-29-21:08', save_which=1, seed=1, start_frame=1, time_step=0.4995004995004995, uid=None, use_cuda=True, use_cudnn=1, weight_decay=0, workers=8)
cudnn is used
Interpolate 1 frames
Traceback (most recent call last):
  File "colab_interpolate.py", line 32, in <module>
    pretrained_dict = torch.load(model_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 526, in load
    if _is_zipfile(opened_file):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 76, in _is_zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found
```

How do I fix?

**Comment by CheezyAmuzus** [comment]
Nevermind. I found out it was because I was using the Tesla processor. As soon as I used a different one it worked completely fine.
